language: python
python:
  - "2.7"
  - "3.4"
sudo: required
cache: pip
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements/production.txt"
  - "pip install -r requirements/testing.txt"
  - "pip install ."
before_script:
  - wget -q http://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz
  - tar -xf ffmpeg-*.tar.xz -v
  - sudo mv ffmpeg*/ff* /usr/bin/
  - ffmpeg -version
  - convert --version
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27,coverage; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then tox -e py34; fi
