language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install -qq imagemagick ffmpeg
install:
  - "pip install -r requirements/production.txt"
  - "pip install -r requirements/testing.txt"
  - "pip install ."
script:
  - tox -e py27,coverage