language: python
python:
  - "2.7"
  - "3.4"
sudo: required
install:
  - "pip install -r requirements/production.txt"
  - "pip install -r requirements/testing.txt"
  - "pip install ."
before_script:
  - sudo add-apt-repository ppa:jon-severinsson/ffmpeg -y
  - sudo apt-get update -q
  - sudo apt-get install imagemagick ffmpeg
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then tox -e py27,coverage; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then tox -e py34; fi