language: python
python:
  - "2.7"
install:
  - "pip install -r requirements/production.txt"
  - "pip install -r requirements/testing.txt"
  - "pip install ."
before_script:
  - sudo add-apt-repository ppa:jon-severinsson/ffmpeg -y
  - sudo apt-get update -q
  - sudo apt-get install imagemagick ffmpeg
script:
  - tox -e py27,coverage