# Generated by Django 2.2.17 on 2021-01-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encode', '0002_auto_20151125_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='mediabase_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='encode.MediaBase'),
        ),
        migrations.AlterField(
            model_name='mediabase',
            name='keep_input_file',
            field=models.BooleanField(default=True, help_text="Indicates that the input file should be saved and not\n            be removed after it's encoded and uploaded.", verbose_name='Keep input file'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='mediabase_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='encode.MediaBase'),
        ),
        migrations.AlterField(
            model_name='video',
            name='mediabase_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='encode.MediaBase'),
        ),
    ]
