# Generated by Django 2.2.17 on 2021-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encode', '0003_auto_20210118_0218'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='mediafile',
        #     name='extract',
        #     field=models.BooleanField(default=False, help_text='Is it an extract ?', verbose_name='Extract'),
        # ),
    ]
