# Generated by Django 2.2.17 on 2021-01-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encode', '0004_mediafile_extract'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='mediafile',
        #     name='extract',
        # ),
        migrations.AddField(
            model_name='mediabase',
            name='extract',
            field=models.BooleanField(default=False, help_text='Is it an extract ?', verbose_name='Extract'),
        ),
    ]
