# Generated by Django 2.2.17 on 2021-01-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encode', '0006_auto_20210127_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediabase',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration of the media in seconds', null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='mediabase',
            name='extract_duration',
            field=models.FloatField(blank=True, help_text='Duration of extract in seconds', null=True, verbose_name='Extract duration'),
        ),
    ]
